#! /usr/bin/env python
# encoding: utf-8

VERSION='0.0.1'
APPNAME='volume_mesher'  

top = '.'
out = 'build'

localtoolsdir = 'waftools/'

def options(ctx):
   ctx.load('g++')
   ctx.load('boost', tooldir=localtoolsdir)   

def configure(ctx):
   ctx.load('g++')
   ctx.check_boost()
   ctx.env.append_value('CXXFLAGS', ['-O2', '-fPIC'])

def build(ctx):

   #
   #  build the converter library
   #
   ctx(
      features     = 'cxx cxxprogram', 
      source       = 'src/main.cpp',
      target       = 'mesh_classifier',
      name         = 'mesh_classifier',
      includes     = '. src/ external/gml \
         external/gssev02 external/gssev02/external',
      uselib       = 'BOOST'
   )









