   

include(FindPackageHandleStandardArgs)
find_package(PkgConfig)


# INCLUDE PART
FIND_PATH(VIENNAGRID_INCLUDE_DIR viennagrid/domain.hpp ${VIENNAGRID_INC_DIR})
# ... include base directory and external directory ..
set(VIENNAGRID_INCLUDE_DIRS ${VIENNAGRID_INCLUDE_DIR})
find_package_handle_standard_args(VIENNAGRID_INC DEFAULT_MSG VIENNAGRID_INCLUDE_DIR)
MARK_AS_ADVANCED(VIENNAGRID_INCLUDE_DIR)
IF( NOT VIENNAGRID_INC_FOUND )
   IF( VIENNAGRID_FIND_REQUIRED ) 
      message(FATAL_ERROR "VIENNAGRID Include directory has not been found")
   ENDIF( VIENNAGRID_FIND_REQUIRED )
ENDIF( NOT VIENNAGRID_INC_FOUND )


# GENERAL PART
IF(VIENNAUTILS_INC_FOUND)
   SET(ENABLE_VIENNAUTILS ON)
ENDIF(VIENNAUTILS_INC_FOUND)

