   

include(FindPackageHandleStandardArgs)
find_package(PkgConfig)


# INCLUDE PART
FIND_PATH(VIENNAUTILS_INCLUDE viennautils/version.hpp ${VIENNAUTILS_INC_DIR})
# ... include base directory and external directory ..
set(VIENNAUTILS_INCLUDE_DIRS ${VIENNAUTILS_INCLUDE} ${VIENNAUTILS_INCLUDE}/external)
set(VIENNAUTILS_INCLUDE_DIRS ${VIENNAUTILS_INCLUDE_DIRS} ${VIENNAUTILS_INCLUDE}/external/)
find_package_handle_standard_args(VIENNAUTILS_INC DEFAULT_MSG VIENNAUTILS_INCLUDE)
MARK_AS_ADVANCED(VIENNAUTILS_INCLUDE)
IF( NOT VIENNAUTILS_INC_FOUND )
   IF( VIENNAUTILS_FIND_REQUIRED ) 
      message(FATAL_ERROR "ViennaUtils Include directory has not been found")
   ENDIF( VIENNAUTILS_FIND_REQUIRED )
ENDIF( NOT VIENNAUTILS_INC_FOUND )


# GENERAL PART
IF(VIENNAUTILS_INC_FOUND)
#   IF(VIENNAUTILS_LIB_FOUND)
      SET(ENABLE_VIENNAUTILS ON)
#   ENDIF(VIENNAUTILS_LIB_FOUND)
ENDIF(VIENNAUTILS_INC_FOUND)

